### ISSUE TITLE
Fehlermeldung „.“ am Ende des Namens

### ISSUE THREAD

**Issue by eric2905** [ticaki/ioBroker.espresense#11]
Adapterversion 0.4.1
Node 18.17.1
Js-controller 5.0.17

Adapter installiert und 1 x ESPresence-Sensor per MQTT (ext. MQTT auf iobroker) angebunden.

Er schreibt mir das Log im Sekundentakt voll:
```
espresense.0
2024-01-02 06:10:32.389	error	Error: The id "rooms.wohnzimmer." is invalid. Ids are not allowed to end in "." 
```

Ich habe aber nirgendwo den Punkt definiert … in ESPresence selber heißt das Teil nur „Wohnzimmer“
Siehe auch Post im Forum : [Link](https://forum.iobroker.net/topic/71189/test-adapter-espresense/16)

VG,
Eric (eric2905)

**Comment by ticaki** [comment]
War heute an dem nspanel skript dran und hab nix mitbekommen. Ich bräuchte das Debuglog 2 Sekunden vor dem Fehler bis zum Fehler.

**Comment by eric2905** [comment]
Manchmal hasse ich IT ... 
Jetzt kommt der Fehler nicht mehr ... kein Reboot, keine Updates, alles wie heute früh auch ....

Case closed (for the moment?)
