### ISSUE TITLE
Konfiguration der ESPresense Sensoren wird zerschossen und zwar bei beiden gleichzeitig

### ISSUE THREAD

**Issue by Flying-Bolt** [ticaki/ioBroker.espresense#27]
Ich habe dann einen zusätzlichen iTag auf diese Weise konfiguriert. Danach liefen die Sensoren nicht mehr und befanden sich im Bootloop. Ich überprüfte die Konfiguration der Sensoren, nachdem ich zuerst die MQTT- und ESPresense-Adapter gestoppt und alle Datenpunkte dieser Adapter gelöscht hatte. Nachdem ich die Adapter wieder startete, kamen die Sensoren aus dem Bootloop.

Die Basis-Konfigurationen der Adapter waren unverändert, aber die Einstellungen waren bei allen Sensoren komplett zerstört. Da standen so Werte wie "Null" drin. Ich musste diese Einstellungen wieder korrigieren, danach begannen sie wieder, MQTT-Daten zu senden, nur leider nicht mehr so wie vorher. Einige iTags wurden nicht mehr erkannt. Erst ein erneutes Flashen der Sensoren hat alle Problem behoben. Das heißt, es werden auch noch Sensorkonfigurationsdaten zerstört, die über die Einstellungen nicht verändert/angepast werden können.

(ÄTZEND)

**Comment by ticaki** [comment]
War ne Zeit lang krank, bei mir läufts noch immer alles in der Basisconfiguration
